---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bar-app
  labels:
    app: bar
spec:
  selector:
    matchLabels:
      app: bar
  replicas: 1
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
      - name: echo
        image: 419030450067.dkr.ecr.us-east-1.amazonaws.com/ms-finances
        args:
        - "-text=bar"
        ports:
        - containerPort: 9000
          protocol: TCP
        resources:
          requests:
            cpu: 200m