apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ms-products
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MatheusFelipeMarinho/kind-kong.git
    targetRevision: HEAD
    path: apps/ms-products
  destination:
    server: https://kubernetes.default.svc
    namespace: ms-products
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
